// <auto-generated />
using System;
using AlphaChannel.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlphaChannel.Server.Data.Migrations
{
    [DbContext(typeof(AlphaChannelDbContext))]
    [Migration("20260806020117_AddLalafellOnboarding")]
    partial class AddLalafellOnboarding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlphaChannel.Server.Data.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BanReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BannedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("DmPublicKey")
                        .HasColumnType("bytea");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLalafell")
                        .HasColumnType("boolean");

                    b.Property<int>("LalafellSocialStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LodestoneCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LodestoneRaceMismatch")
                        .HasColumnType("boolean");

                    b.Property<string>("SelfReportedRaces")
                        .HasColumnType("text");

                    b.Property<bool>("WantsToSeeLalafellContent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Handle")
                        .IsUnique();

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AlphaChannel.Server.Data.AccountCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("World")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CharacterName", "World")
                        .IsUnique();

                    b.ToTable("AccountCharacters");
                });

            modelBuilder.Entity("AlphaChannel.Server.Data.ActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "CreatedAtUtc");

                    b.ToTable("ActivityEvents");
                });

            modelBuilder.Entity("AlphaChannel.Server.Data.AuthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("AuthTokens");
                });

            modelBuilder.Entity("AlphaChannel.Server.Data.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockedAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockerAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BlockerAccountId", "BlockedAccountId")
                        .IsUnique();

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("AlphaChannel.Server.Data.DmConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountBId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountAId", "AccountBId")
                        .IsUnique();

                    b.ToTable("DmConversations");
                });

            modelBuilder.Entity("AlphaChannel.Server.Data.DmMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "SentAtUtc");

                    b.ToTable("DmMessages");
                });

            modelBuilder.Entity("AlphaChannel.Server.Data.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddresseeAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequesterAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeAccountId");

                    b.HasIndex("RequesterAccountId", "AddresseeAccountId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("AlphaChannel.Server.Data.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportedAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReportedMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AlphaChannel.Server.Data.ServerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HideLalafellFromNonLalafell")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HideLalafellFromNonLalafell = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
